name: meme_generator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.2.3 # Dart SDK version
  flutter: 3.16.3 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.0
  share_plus: ^7.2.2
  flutter_sharing_intent: ^1.1.1
  path_provider: ^2.1.2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true